name = "ac-library"
version = "0.0.1"
defaultTargets = ["ACLibrary"]

[[lean_lib]]
name = "ACLibrary"

[[lean_exe]]
name = "ac-library"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.17.0"
